"""첫 배포용 초기 스키마입니다.

2026-09-16 이전의 migration 36개를 하나로 통합했습니다. 옛 파일은 trash/2026-09-16-migration-squash/
에 있습니다. 통합 전후의 스키마가 같다는 것은 빈 DB 두 개에 각각 적용한 뒤 pg_dump 결과를 비교해
확인했습니다.

이 시점 이후로는 스키마를 변경할 때마다 이 파일 뒤에 migration 을 하나씩 더합니다.

Revision ID: 080a74e46f56
Revises:
Create Date: 2026-09-16
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "080a74e46f56"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 이 시점의 팀 색입니다. migration 은 지나간 시점을 그대로 재현해야 하므로 db/models.py 를
# 참조하지 않습니다. 색을 추가·삭제할 때는 새 migration 을 더합니다.
TEAM_COLORS = (
    "tomato", "red", "crimson", "pink", "plum", "purple", "iris", "indigo", "blue", "sky",
    "teal", "jade", "green", "mint", "lime", "yellow", "amber", "orange", "gold", "brown",
)
PALETTE = "ARRAY[{}]::text[]".format(", ".join(f"'{name}'" for name in TEAM_COLORS))

# 이 시점의 권한 항목입니다. 전 항목을 가진 permission set 하나를 아래에서 만듭니다.
PERMISSIONS = (
    "room_create", "room_edit", "period_create", "period_edit", "period_delete",
    "team_create", "team_edit", "team_delete", "member_add", "member_remove",
    "member_expel", "notice_write", "board_moderate", "reservation_manage",
    "assign_run", "assign_read", "proposal_confirm", "rollback",
    "permission_manage", "permission_grant",
)
PERMISSION_ARRAY = "ARRAY[{}]::text[]".format(", ".join(f"'{name}'" for name in PERMISSIONS))
FULL_SET_NAME = "헤드매니저"
# 점유 단위의 기본값입니다. db/models.py 의 DEFAULT_SLOT_MINUTES 와 같은 값이지만,
# migration 은 지나간 시점을 그대로 재현해야 하므로 참조하지 않고 여기에 적습니다.
DEFAULT_SLOT_MINUTES = 60


def upgrade() -> None:
    """Upgrade schema."""
    # gist index 는 범위·기하 자료형만 다룹니다. room_id 같은 정수를 = 로 함께
    # 묶으려면 이 확장이 필요합니다(아래 EXCLUDE 제약).
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('student_no', sa.Text(), nullable=True),
    sa.Column('cohort', sa.Integer(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name', 'department', 'student_no', 'cohort')
    )
    op.create_table('permission_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.CheckConstraint("permissions <@ ARRAY['room_create', 'room_edit', 'period_create', 'period_edit', 'period_delete', 'team_create', 'team_edit', 'team_delete', 'member_add', 'member_remove', 'member_expel', 'notice_write', 'board_moderate', 'reservation_manage', 'assign_run', 'assign_read', 'proposal_confirm', 'rollback', 'permission_manage', 'permission_grant']::text[]", name='permission_sets_permissions_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.CheckConstraint("date_part('minute', closes_at) = 0 AND date_part('second', closes_at) = 0"),
    sa.CheckConstraint("date_part('minute', opens_at) = 0 AND date_part('second', opens_at) = 0"),
    sa.CheckConstraint('closes_at > opens_at', name='rooms_closes_after_opens'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.CheckConstraint('id = 1'),
    sa.CheckConstraint('slot_minutes BETWEEN 5 AND 60 AND 60 % slot_minutes = 0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), server_default=sa.FetchedValue(), nullable=False),
    sa.CheckConstraint("color = ANY (ARRAY['tomato', 'red', 'crimson', 'pink', 'plum', 'purple', 'iris', 'indigo', 'blue', 'sky', 'teal', 'jade', 'green', 'mint', 'lime', 'yellow', 'amber', 'orange', 'gold', 'brown']::text[])", name='teams_color_valid'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color'),
    sa.UniqueConstraint('name')
    )
    op.create_table('member_permission_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('permission_set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_set_id'], ['permission_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'permission_set_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("kind IN ('assignment_updated')"),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_member_id'), 'notifications', ['member_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('everyday', sa.Boolean(), nullable=False),
    sa.Column('first_run_at', sa.Time(), nullable=False),
    sa.Column('second_run_at', sa.Time(), nullable=False),
    sa.Column('ensemble_starts_on', sa.Date(), nullable=True),
    sa.Column('ensemble_ends_on', sa.Date(), nullable=True),
    sa.Column('ensemble_room_id', sa.Integer(), nullable=True),
    sa.Column('ensemble_starts_at', sa.Time(), nullable=True),
    sa.Column('ensemble_ends_at', sa.Time(), nullable=True),
    sa.CheckConstraint("ensemble_starts_on IS NULL OR kind = 'focused'", name='periods_ensemble_focused_only'),
    sa.CheckConstraint("kind IN ('open', 'focused')"),
    sa.CheckConstraint('ends_on >= starts_on'),
    sa.CheckConstraint('ensemble_ends_at > ensemble_starts_at', name='periods_ensemble_times_order'),
    sa.CheckConstraint('ensemble_starts_on IS NULL OR (ensemble_starts_on >= starts_on AND ensemble_ends_on >= ensemble_starts_on AND (everyday OR ensemble_ends_on <= ends_on))', name='periods_ensemble_within_period'),
    sa.CheckConstraint('num_nulls(ensemble_starts_on, ensemble_ends_on, ensemble_room_id, ensemble_starts_at, ensemble_ends_at) IN (0, 5)', name='periods_ensemble_all_or_none'),
    sa.ForeignKeyConstraint(['ensemble_room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('blinded_at', sa.DateTime(), nullable=True),
    sa.Column('blinded_by_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('published_at IS NULL OR length(trim(body)) > 0', name='posts_published_body'),
    sa.CheckConstraint('published_at IS NULL OR length(trim(title)) > 0', name='posts_published_title'),
    sa.ForeignKeyConstraint(['author_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blinded_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_team_id'), 'posts', ['team_id'], unique=False)
    op.create_index('ix_posts_visible', 'posts', ['team_id'], unique=False, postgresql_where=sa.text('blinded_at IS NULL AND published_at IS NOT NULL'))
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('ends_at > starts_at'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservations_room_starts_at', 'reservations', ['room_id', 'starts_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('team_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("instrument IN ('보컬', '일렉', '통기타', '베이스', '신디', '드럼')"),
    sa.CheckConstraint('ordinal >= 1'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'instrument', 'ordinal'),
    sa.UniqueConstraint('team_id', 'member_id')
    )
    op.create_table('unavailable_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('repeats_daily', sa.Boolean(), nullable=False),
    sa.Column('repeats_weekly', sa.Boolean(), nullable=False),
    sa.Column('repeat_until', sa.Date(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.CheckConstraint('ends_at > starts_at'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('ends_at > starts_at'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('run_on', sa.Date(), nullable=False),
    sa.Column('slot', sa.Text(), nullable=False),
    sa.Column('ran_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("slot IN ('first', 'second')"),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'run_on', 'slot')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('ends_at > starts_at'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assignments_room_starts_at', 'assignments', ['room_id', 'starts_at'], unique=False)
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('stored_name', sa.Text(), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0'),
    sa.CheckConstraint('size >= 0'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index(op.f('ix_attachments_post_id'), 'attachments', ['post_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(body)) > 0', name='comments_body_not_blank'),
    sa.ForeignKeyConstraint(['author_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_table('ensemble_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.CheckConstraint('ends_at > starts_at'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_id', 'day')
    )
    # ### end Alembic commands ###

    # 아래는 SQLAlchemy 로 표현되지 않아 직접 적습니다.

    # 같은 합주실의 시간이 겹치는 것을 DB 가 막습니다. tsrange 는 시작과 끝으로 만든 시각
    # 구간이고 && 는 두 구간이 겹친다는 뜻입니다. 앱 코드로 확인하면 두 요청이 같은 순간에
    # 들어올 때 둘 다 통과합니다.
    op.execute(
        "ALTER TABLE assignments ADD CONSTRAINT assignments_no_overlap "
        "EXCLUDE USING gist (room_id WITH =, tsrange(starts_at, ends_at) WITH &&)"
    )
    # 취소한 예약은 행을 남기므로(cancelled_at) 겹침 판정에서 제외합니다.
    op.execute(
        "ALTER TABLE reservations ADD CONSTRAINT reservations_no_overlap "
        "EXCLUDE USING gist (room_id WITH =, tsrange(starts_at, ends_at) WITH &&) "
        "WHERE (cancelled_at IS NULL)"
    )
    # 집중 합주기간끼리는 날짜가 겹칠 수 없습니다. everyday 기간은 종료일이 없으므로
    # daterange 의 끝을 NULL 로 두어 무한으로 만듭니다. '[]' 는 양끝을 포함한다는 뜻입니다.
    op.execute(
        f"ALTER TABLE periods ADD CONSTRAINT periods_focused_no_overlap EXCLUDE USING gist "
        "(daterange(starts_on, CASE WHEN everyday THEN NULL ELSE ends_on END, '[]') WITH &&) "
        "WHERE (kind = 'focused')"
    )

    # 색을 선택하지 않고 만든 팀에 다른 팀이 쓰지 않는 첫 색을 채웁니다. 앱 코드에서
    # 선택하게 하면 팀을 INSERT 하는 모든 곳(서비스·스크립트·테스트)이 색을 알아야 합니다.
    # 남은 색이 없으면 제약 이름(teams_color_exhausted)을 붙여 거절합니다. 이름 없이
    # NOT NULL 에 걸리게 두면 서버가 문장으로 변환할 수 없어 500 이 됩니다.
    # ERRCODE check_violation 은 23 계열이라 드라이버가 IntegrityError 로 올립니다.
    op.execute(
        "CREATE FUNCTION teams_pick_color() RETURNS trigger LANGUAGE plpgsql AS $$"
        " BEGIN"
        "   IF NEW.color IS NULL THEN"
        "     SELECT palette.c INTO NEW.color"
        f"    FROM unnest({PALETTE}) WITH ORDINALITY AS palette(c, i)"
        "     WHERE NOT EXISTS (SELECT 1 FROM teams WHERE teams.color = palette.c)"
        "     ORDER BY palette.i LIMIT 1;"
        "     IF NEW.color IS NULL THEN"
        "       RAISE EXCEPTION 'no free team color'"
        "         USING ERRCODE = 'check_violation', CONSTRAINT = 'teams_color_exhausted';"
        "     END IF;"
        "   END IF;"
        "   RETURN NEW;"
        " END $$"
    )
    op.execute(
        "CREATE TRIGGER teams_pick_color BEFORE INSERT ON teams"
        " FOR EACH ROW EXECUTE FUNCTION teams_pick_color()"
    )

    # 여기부터는 스키마가 아니라 초기 데이터입니다. 빈 DB 가 이 두 행 없이 뜨면
    # 설정 조회가 RuntimeError 로 멈추고, 권한을 부여할 permission set 이 없습니다.

    # 설정은 한 행만 존재합니다(CHECK id = 1). 읽는 쪽이 "행이 없는 경우" 를 따로
    # 다루지 않도록 여기서 넣습니다.
    op.execute(f"INSERT INTO settings (id, slot_minutes) VALUES (1, {DEFAULT_SLOT_MINUTES})")
    # 관리자코드로 가입한 첫 계정이 이 permission set 을 받습니다.
    op.execute(
        "INSERT INTO permission_sets (name, description, permissions)"
        f" VALUES ('{FULL_SET_NAME}', '', {PERMISSION_ARRAY})"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ensemble_days')
    # table 을 삭제하면 그 table 의 제약과 트리거도 함께 삭제되지만, 함수는 table 에
    # 딸린 것이 아니라 따로 남습니다.
    op.execute("DROP TRIGGER IF EXISTS teams_pick_color ON teams")
    op.execute("DROP FUNCTION IF EXISTS teams_pick_color()")
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_attachments_post_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_assignments_room_starts_at', table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('assignment_runs')
    op.drop_table('assignment_backups')
    op.drop_table('unavailable_times')
    op.drop_table('team_slots')
    op.drop_table('sessions')
    op.drop_index('ix_reservations_room_starts_at', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('ix_posts_visible', table_name='posts', postgresql_where=sa.text('blinded_at IS NULL AND published_at IS NOT NULL'))
    op.drop_index(op.f('ix_posts_team_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('periods')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_member_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('member_permission_sets')
    op.drop_table('teams')
    op.drop_table('settings')
    op.drop_table('rooms')
    op.drop_table('permission_sets')
    op.drop_table('members')
    # ### end Alembic commands ###
