"""unavailable times and rooms

Revision ID: 08a3734da800
Revises: 072758eb0033
Create Date: 2026-07-21 08:04:41.881157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a3734da800'
down_revision: Union[str, Sequence[str], None] = '072758eb0033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.CheckConstraint("date_part('minute', closes_at) IN (0, 30) AND date_part('second', closes_at) = 0"),
    sa.CheckConstraint("date_part('minute', opens_at) IN (0, 30) AND date_part('second', opens_at) = 0"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unavailable_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('repeats_weekly', sa.Boolean(), nullable=False),
    sa.Column('repeat_until', sa.Date(), nullable=True),
    sa.CheckConstraint('ends_at > starts_at'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unavailable_times')
    op.drop_table('rooms')
    # ### end Alembic commands ###
