"""board content constraints and indexes

Revision ID: 92d0d767d186
Revises: e32b20253fc7
Create Date: 2026-09-04 04:06:57.954003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d0d767d186'
down_revision: Union[str, Sequence[str], None] = 'e32b20253fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 손수 추가 — autogenerate는 CHECK 제약을 잡아내지 못한다(fd4b8458697a와 같은 이유).
    # 공백만 있는 제목·본문·댓글이 경계 검증을 거치지 않고 들어오는 것을 DB에서도 막는다.
    op.create_check_constraint(
        "posts_title_not_blank", "posts", "length(trim(title)) > 0"
    )
    op.create_check_constraint(
        "posts_body_not_blank", "posts", "length(trim(body)) > 0"
    )
    op.create_check_constraint(
        "comments_body_not_blank", "comments", "length(trim(body)) > 0"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_posts_team_id'), 'posts', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("comments_body_not_blank", "comments", type_="check")
    op.drop_constraint("posts_body_not_blank", "posts", type_="check")
    op.drop_constraint("posts_title_not_blank", "posts", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_team_id'), table_name='posts')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    # ### end Alembic commands ###
