"""정책 table을 삭제하고 집중 합주기간의 시작·종료 시각을 필수로 설정합니다.

Revision ID: fd4b8458697a
Revises: 9f358ed961f2
Create Date: 2026-07-21 08:46:25.209564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd4b8458697a'
down_revision: Union[str, Sequence[str], None] = '9f358ed961f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """정책 table을 삭제하고 집중 합주기간의 시작·종료 시각을 필수로 설정합니다."""

    # 수동 추가 1: 합주실의 닫는 시각이 여는 시각보다 뒤에 와야 한다는 제약 조건입니다.
    # Alembic의 autogenerate는 CHECK constraint를 감지하지 못하므로 기존 slot(1시간 단위
    # 시간 칸) CHECK constraint 두 개와 함께 수동으로 추가합니다.
    op.create_check_constraint(
        "rooms_closes_after_opens", "rooms", "closes_at > opens_at"
    )

    # 수동 추가 2: period table의 first_run_at·second_run_at을 NOT NULL로 변경하기 전에,
    # 이미 저장된 NULL 행을 기본값으로 채웁니다. 반드시 아래 alter_column(NOT NULL 지정)
    # 전에 실행되어야 변경 실패를 방지할 수 있습니다.
    # (migration(DB 구조를 바꾸는 단계별 기록) 작성 시점에 실제 periods table은 비어 있었지만,
    # 운영 데이터가 쌓인 뒤 이 migration이 다시 적용될 가능성을 방지하기 위해 방어적으로
    # 추가합니다.)
    op.execute(
        "UPDATE periods SET first_run_at = '09:00', second_run_at = '21:00'"
        " WHERE first_run_at IS NULL OR second_run_at IS NULL"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assignments_period_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_team_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_room_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignments', 'periods', ['period_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignments', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('memberships_member_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('memberships_position_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('memberships_team_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'positions', ['position_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('periods', 'first_run_at',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('periods', 'second_run_at',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.drop_constraint(op.f('unavailable_times_member_id_fkey'), 'unavailable_times', type_='foreignkey')
    op.create_foreign_key(None, 'unavailable_times', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """정책 table을 복원하고 집중 합주기간의 시작·종료 시각을 선택사항으로 변경합니다."""
    op.drop_constraint("rooms_closes_after_opens", "rooms", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    # upgrade에서 이름 없이 생성한 foreign key는 PostgreSQL이 <table>_<column>_fkey
    # 형식으로 이름을 붙입니다.
    op.drop_constraint('unavailable_times_member_id_fkey', 'unavailable_times', type_='foreignkey')
    op.create_foreign_key(op.f('unavailable_times_member_id_fkey'), 'unavailable_times', 'members', ['member_id'], ['id'])
    op.alter_column('periods', 'second_run_at',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('periods', 'first_run_at',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.drop_constraint('memberships_member_id_fkey', 'memberships', type_='foreignkey')
    op.drop_constraint('memberships_team_id_fkey', 'memberships', type_='foreignkey')
    op.drop_constraint('memberships_position_id_fkey', 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_team_id_fkey'), 'memberships', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('memberships_position_id_fkey'), 'memberships', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(op.f('memberships_member_id_fkey'), 'memberships', 'members', ['member_id'], ['id'])
    op.drop_constraint('assignments_team_id_fkey', 'assignments', type_='foreignkey')
    op.drop_constraint('assignments_period_id_fkey', 'assignments', type_='foreignkey')
    op.drop_constraint('assignments_room_id_fkey', 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_room_id_fkey'), 'assignments', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('assignments_team_id_fkey'), 'assignments', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('assignments_period_id_fkey'), 'assignments', 'periods', ['period_id'], ['id'])
    # ### end Alembic commands ###
