"""delete policies and required run times

Revision ID: fd4b8458697a
Revises: 9f358ed961f2
Create Date: 2026-07-21 08:46:25.209564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd4b8458697a'
down_revision: Union[str, Sequence[str], None] = '9f358ed961f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # 손수 추가 1: 방 여닫는 시각 순서 제약. autogenerate는 CHECK 제약을 잡아내지
    # 못하므로 이미 있는 시각 격자 CHECK 두 개와 나란히 손으로 추가한다.
    op.create_check_constraint(
        "rooms_closes_after_opens", "rooms", "closes_at > opens_at"
    )

    # 손수 추가 2: periods.first_run_at/second_run_at을 NOT NULL로 바꾸기 전에,
    # 이미 들어가 있을 수 있는 NULL 행을 기본값으로 채운다. 반드시 아래 alter_column
    # (NOT NULL 부여)보다 먼저 실행되어야 alter가 실패하지 않는다.
    # (마이그레이션 작성 시점에 실제 periods 테이블은 비어 있었지만, 운영 데이터가
    # 쌓인 뒤 이 마이그레이션이 재적용될 가능성을 막기 위해 방어적으로 넣는다.)
    op.execute(
        "UPDATE periods SET first_run_at = '09:00', second_run_at = '21:00'"
        " WHERE first_run_at IS NULL OR second_run_at IS NULL"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assignments_period_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_team_id_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_room_id_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignments', 'periods', ['period_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignments', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('memberships_member_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('memberships_position_id_fkey'), 'memberships', type_='foreignkey')
    op.drop_constraint(op.f('memberships_team_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'positions', ['position_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('periods', 'first_run_at',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('periods', 'second_run_at',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.drop_constraint(op.f('unavailable_times_member_id_fkey'), 'unavailable_times', type_='foreignkey')
    op.create_foreign_key(None, 'unavailable_times', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("rooms_closes_after_opens", "rooms", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unavailable_times', type_='foreignkey')
    op.create_foreign_key(op.f('unavailable_times_member_id_fkey'), 'unavailable_times', 'members', ['member_id'], ['id'])
    op.alter_column('periods', 'second_run_at',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('periods', 'first_run_at',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_team_id_fkey'), 'memberships', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('memberships_position_id_fkey'), 'memberships', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(op.f('memberships_member_id_fkey'), 'memberships', 'members', ['member_id'], ['id'])
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_room_id_fkey'), 'assignments', 'rooms', ['room_id'], ['id'])
    op.create_foreign_key(op.f('assignments_team_id_fkey'), 'assignments', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('assignments_period_id_fkey'), 'assignments', 'periods', ['period_id'], ['id'])
    # ### end Alembic commands ###
